title: Mike's Projects
author: Mike
email: kirillovsleaf@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A place for my Arduino projects, and C++ programs

# social links

github_username:  Friedrich-von-Cool

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
